theme: jekyll-theme-leap-day
# remote_theme: pages-themes/tactile@v0.2.0
# plugins:
# - jekyll-remote-theme 

# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme

title: COSE&nu;
description: A sofisticated simulation engine for collective neutrino oscillations
lsi: false
safe: true

incremental: false
gist:
  noscript: false

markdown: kramdown
highlighter: rouge
input: GFM
math_engine: mathjax

